### ISSUE TITLE
polarization filter angle in rad instead of degrees

### ISSUE THREAD

**Issue by riddlecul** [MartinPdeS/PyMieSim#14]
Contrary to all other angles (gamma_offset, phi_offset, source polarization_value) which are to be given in degrees, the detector's polarization_filter is to be given in rad. This is not documented and also the default plots show it as if were degrees. I'd suggest to changing to degrees for consitency with the other angles.

**Comment by MartinPdeS** [comment]
The problem was fixed in the new 1.6.6 version, unit tests for consistency assertion were added too.

**Comment by riddlecul** [comment]
Luckily, it was easy to fix. Works as expected now - thanks for fixing it so quickly!
