### ISSUE TITLE
PyMieSim does not match other Mie scattering libraries

### ISSUE THREAD

**Issue by runrunm** [MartinPdeS/PyMieSim#36]
Hello,

First thank you for developing PyMieSim !

I was experimenting with PyMieSim on an homogeneous sphere and tried to compare obtained efficiencies with other Mie libraries/tools (PyMieScatt, Miepython and [Saviot CNRS](https://saviot.cnrs.fr/mie/index.html)). I used a PlaneWave source (working since PyMieSim 2.4.2) with a wavelength range from 200 to 1200 nm (with 10 nm steps). I used a gold 50 nm sphere with index properties retrieved from PyOptik library and with a medium index n=1.5.
All efficiencies overlap perfectly except for PyMieSim's one (it's close but still the difference is there) and it also happens for other materials than gold. I wonder what can cause this difference, I didn't find anything about the interpolation PyMieSim uses, could it be something related to this ? What other things could be verified ? (All the index data comes from Johnson & Christy index database).

![gold_sphere_50nm_pymiesim_no_overlap](https://github.com/user-attachments/assets/65e193ee-08f0-4de3-9226-c6193a125ebf)

Thanks for the help !

Bastien

**Comment by MartinPdeS** [comment]
Hi Bastien, thanks for reaching out about this problem.
To run the example on my side, can you provide the source code? At least for PyMieScatt and for PyMieSim?
PyMieSim actually updates the material refractive index depending on the source wavelength that is provided, which is not the case for PyMieScatt. I reckon this might be a source for the discrepancy.

**Comment by runrunm** [comment]
Here is the code for PyMieSim and PyMieScatt. I also use PyOptik for the data used by PyMieScatt, only I manually do a linear interpolation using the **get_m()** function.

```
import numpy as np
import matplotlib.pyplot as plt
import PyMieScatt

from PyMieSim.experiment.source import Gaussian, PlaneWave
from PyMieSim.experiment.scatterer import Sphere
from PyMieSim.experiment import Setup
from PyMieSim.polarization import Linear
from PyMieSim.units import nanometer, degree, watt, AU, RIU
from PyOptik import Material

def get_m(material, wl_range):
    n_list = list(material.n_values)
    k_list = list(material.k_values)
    wl_mat_um = list(material.wavelength)
    wl_mat = [wl_mat_um[i]*1e3 for i in range(len(wl_mat_um))]

    # Linear interpolation
    n_interp = np.interp(wl_range, wl_mat, n_list)
    k_interp = np.interp(wl_range, wl_mat, k_list)

    # Create complex index array from interpolated values
    m = np.array([complex(n_interp[i], k_interp[i]) for i in range(len(n_interp))])
    
    return m

wl_range = np.linspace(200, 1200, 100)  # Wavelength range in nanometers

material = Material.gold
r = 25   # particle radius in nanometers
d = 2*r  # diameter
n_medium = 1.5  # medium index

#%% PyMieSim
source = PlaneWave(
    wavelength=wl_range * nanometer,
    polarization=0 * degree,
    amplitude=0 * watt,
)

scatterer = Sphere(
    diameter=d * nanometer,
    property=material,
    medium_property=n_medium * RIU,
    source=source
)
experiment = Setup(
    scatterer=scatterer,
    source=source,
)

qsca_pymiesim = experiment.get('Qsca', add_units=False).squeeze().tolist()
qabs_pymiesim = experiment.get('Qabs', add_units=False).squeeze().tolist()
qext_pymiesim = experiment.get('Qext', add_units=False).squeeze().tolist()

#%% PyMieScatt
m = get_m(material, wl_range)  # Interpolated complex indices array of the particle material

_, qext_pymiescatt, qsca_pymiescatt, qabs_pymiescatt, *_  = PyMieScatt.MieQ_withWavelengthRange(m, d, n_medium, wl_range)

#%% Plotting
fig = plt.figure(figsize=(6,4))
ax = fig.add_subplot(1, 1, 1)
ax.set_title("Scattering efficiencies (miepython vs PyMieScatt vs PyMieSim)")

ax.plot(wl_range, qext_pymiesim,   ls='-', lw=0.5, marker='o', markersize=4, c='tab:green', label=r"$Q_{ext}^{PyMieSim}$")
ax.plot(wl_range, qext_pymiescatt, ls='-', lw=0.5, marker='o', markersize=4, c='tab:orange', label=r"$Q_{ext}^{PyMieScatt}$")
ax.plot(wl_range, qabs_pymiesim,   ls='-', lw=0.5, marker='^', markersize=4, c='tab:green', label=r"$Q_{abs}^{PyMieSim}$")
ax.plot(wl_range, qabs_pymiescatt, ls='-', lw=0.5, marker='^', markersize=4, c='tab:orange', label=r"$Q_{abs}^{PyMieScatt}$")
ax.plot(wl_range, qsca_pymiesim,   ls='-', lw=0.5, marker='s', markersize=4, c='tab:green', label=r"$Q_{sca}^{PyMieSim}$")
ax.plot(wl_range, qsca_pymiescatt, ls='-', lw=0.5, marker='s', markersize=4, c='tab:orange', label=r"$Q_{sca}^{PyMieScatt}$")

plt.xlabel("Wavelength (nm)")
plt.ylabel("Efficiency")
plt.legend()
plt.tight_layout()
plt.show()
```

**Comment by MartinPdeS** [comment]
@runrunm 
Hey, for some reason, I couldn't run your code. Nonetheless, I have rewritten it to look at the problem and on my side it all looks to fit the PyMieScatt data.

I do provide a picture of the data collected here.
![Figure_1](https://github.com/user-attachments/assets/cd688816-c982-4ace-99cb-fa45cf15f53a)


Additionally, I have saved a Google Colab on my drive so you can try it for yourself: [Colab](https://colab.research.google.com/gist/MartinPdeS/6b2f6cd06c7bd6a44b2eff6ba767c59c/notebook.ipynb)

I don't really understand what you mean with interpolation, PyMieSim does not get the refractive index from the material through interpolation but using the Sellmeier coefficients.
Actually, this computation comes from the PyOptik library.

I am looking forward to hearing from you on that matter.

**Comment by runrunm** [comment]
Hello!

Thanks @MartinPdeS  for your reply, I indeed have no issues when using the [`compute_refractive_index`](https://github.com/MartinPdeS/PyOptik/blob/456cae6f03e4f3138021b420577e405c2ea40353/PyOptik/tabulated_class.py) function from PyMieSim to retrieve the n and κ values, either using PyMieScatt or PyMieSim gives a nice overlap when plotting.

However this `compute_refractive_index` is different depending on the type of material you are using (Sellmeier or tabulated). Gold is defined as a TabulatedMaterial and the refractive index is actually interpolated using `scipy.interpolate.interp1d` with `kind` parameter set to `cubic` leading to a different result (I was using `numpy.interp`). This is true with PyOptik 1.6.5 but PyOptik 1.8.4 seems do be different (does not work at first sight on my side). I have not tried PyMieSim on Sellmeier materials yet.

Anyway, I think it could be a nice feature to have the choice on the type of interpolation used and to be able to compute raw data without any interpolation for tabulated materials.

Cheers,

Bastien

**Comment by MartinPdeS** [comment]
@runrunm 
Hi! I am glad to hear that. You are right that I should make the use of Sellmeier or Tabulated Material more obvious, but that will come from the PyOptik side. I am planning on working on this in the upcoming weeks, so beware of version update for PyOptik.
For the moment, using PyOptik 1.8.4 you can do the following:

``` python
import numpy
from PyOptik import MaterialBank
MaterialBank.build_library('classics')
MaterialBank.print_materials()  # <- this will provide a table of Tabulated and Sellmeier materials name (usually metals are tabulated)
material = MaterialBank.gold # <- this should be a TabulatedMaterial instance

wavelength = numpy.linspace(300e-9, 500e-9, 100)

ri = material.compute_refractive_index(wavelength)

```
Additionally, I have dropped the use of SciPy interpolation tools (for PyOptik version 1.8.0+) as it brings too much of baggage to the library. It is now relying on `numpy.interp`. I think it is probably better this way, as the most common interpolation method used is still linear.

I will definitely add up some more details in the documentation in that regard.

I hope this helps you.

While I would enjoy continuing this conversation, I will close the issue now as the problem seems to be resolved on PyMieSim side.
